
---
# configmap for apollo-config-server-test-beta
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: ns-apollo
  name: configmap-apollo-config-server-test-beta
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://service-mysql-for-apollo-test-beta-env.ns-apollo:3306/TestBetaApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = root
    spring.datasource.password = qwe123ASD#@!
    eureka.service.url = http://statefulset-apollo-config-server-test-beta-0.service-apollo-meta-server-test-beta:8080/eureka/

---
kind: Service
apiVersion: v1
metadata:
  namespace: ns-apollo
  name: service-apollo-meta-server-test-beta
  labels:
    app: service-apollo-meta-server-test-beta
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pod-apollo-config-server-test-beta
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: Service
apiVersion: v1
metadata:
  namespace: ns-apollo
  name: service-apollo-config-server-test-beta
  labels:
    app: service-apollo-config-server-test-beta
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31104
  selector:
    app: pod-apollo-config-server-test-beta
  type: NodePort
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  namespace: ns-apollo
  name: statefulset-apollo-config-server-test-beta
  labels:
    app: statefulset-apollo-config-server-test-beta
spec:
  serviceName: service-apollo-meta-server-test-beta
  replicas: 1
  selector:
    matchLabels:
      app: pod-apollo-config-server-test-beta
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-apollo-config-server-test-beta
    spec:
#      nodeSelector:
#        node: "apollo"
      nodeName: kubernetes-node-1
      
      volumes:
        - name: volume-configmap-apollo-config-server-test-beta
          configMap:
            name: configmap-apollo-config-server-test-beta
            items:
              - key: application-github.properties
                path: application-github.properties
      
      containers:
        - image: 10.46.10.36/apollo/apollo-config-server:v1.3.0
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          name: container-apollo-config-server-test-beta
          ports:
            - protocol: TCP
              containerPort: 8080
          
          volumeMounts:
            - name: volume-configmap-apollo-config-server-test-beta
              mountPath: /apollo-config-server/config/application-github.properties
              subPath: application-github.properties
          env:
            - name: APOLLO_CONFIG_SERVICE_NAME
              value: "service-apollo-config-server-test-alpha.ns-apollo"
          
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
          
      dnsPolicy: ClusterFirst
      restartPolicy: Always
