---
kind: Service
apiVersion: v1
metadata:
  namespace: ns-apollo
  name: service-mysql-for-apollo-test-alpha-env
  labels:
    app: service-mysql-for-apollo-test-alpha-env
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  sessionAffinity: None

---
kind: Endpoints
apiVersion: v1
metadata:
  namespace: ns-apollo
  name: service-mysql-for-apollo-test-alpha-env
subsets:
  - addresses:
      - ip: 10.46.91.115
    ports:
      - protocol: TCP
        port: 3306
